### DISCUSSION TITLE
Is there a way to disable line numbers per code-block?

### DISCUSSION THREAD

**Discussion by Guts** [facelessuser/pymdown-extensions#1403] [Q&A] [answered]
I use it through MkDocs and I've enabled it in my configuration:

```yaml
- pymdownx.highlight:
    linenums: true
    use_pygments: true
```

I would like to disable it for some code blocks. Is there something like this:

````markdown
```bash linenums="None"
git status
```
````
