### DISCUSSION TITLE
tabbed/alternate broken on mkdocs-material

### DISCUSSION THREAD

**Discussion by casperdcl** [facelessuser/pymdown-extensions#1552] [Q&A] [answered]
### Description

[mkdocs-material>=8.1.3](https://squidfunk.github.io/mkdocs-material/changelog/#8.1.3) broke #1417 tab linking & scrolling (`tabSync`, `tabOverflow`, `tabScroll`). Note that [mkdocs-material==8.1.2](https://squidfunk.github.io/mkdocs-material/changelog/#8.1.2) works fine.

### Minimal Reproduction

mkdocs config (extra JS & CSS from the docs at https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/#linked-tabs & https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/#alternate-style):

```yaml
  extra_javascript: [js/extra.js]
  extra_css: [css/extra.css]
  theme:
    name: material
    custom_dir: ../../custom_theme/
  markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
```

### Version(s) & System Info

- Python Version: 3.8.12
- Package Version: `mkdocs-material>=8.1.3`, `pymdown-extensions==9.1`
