### DISCUSSION TITLE
How can I use Snippet at the same time as README and index.md?

### DISCUSSION THREAD

**Discussion by AsheKR** [facelessuser/pymdown-extensions#1563] [Q&A] [answered]
My directory structure

```
- README.md
- mkdocs.yml
- assets/
  - image/
    - coverage.svg
- docs/
  - index.md  => --8<-- "README.md"
```

My mkdocs settings
```yml
markdown_extensions:
- pymdownx.snippets:
    check_paths: true
```

"assets/image/coverage.svg" can see it at README.md, but not at index.md.
How can I see them in both places?
