### DISCUSSION TITLE
Is it possible to embed a file which is earlier in the file structure?

### DISCUSSION THREAD

**Discussion by louisonsarlinmagnus** [facelessuser/pymdown-extensions#1581] [Q&A] [answered]
I would like to embed my file `to_embed.md`in `index.md`

**My files:**
```
/my_repo
     to_embed.md
     mkdocs/
     |____README.md
     |____mkdocs.yaml
     |____docs/
          |____index.md
```

**index.md:**
```
--8<-- "to_embed.md"
```

I know that `--8<-- "README.md"` is working, so the default base_path is set to `docs` folder.
I've tried with the `base_path` setting in the mkdocs extension and with a relative path like`--8<-- "../to_embed.md"` but nothing work around.

So I'm wondering if this is something that's doable, or if I've missed something.

Thank you very much

**Comment by facelessuser** [comment, marked as answer]
So, you are running mkdocs from the mkdocs folder, not from the root of your project?

**Reply by louisonsarlinmagnus** [reply]
Yes exactely !

**Reply by facelessuser** [reply]
How are you configuring Snippets?

**Reply by louisonsarlinmagnus** [reply]
The only config I've done is in the `mkdocs.yaml` file.

Here is the configuration:
```
markdown_extensions:
  - pymdownx.snippets:
      auto_append:
      - docs/glossaire.md
```

**Reply by louisonsarlinmagnus** [reply]
This `docs/glossaire.md` is a file where I store abbreviations

**Reply by facelessuser** [reply]
Often, I put all of my snippets in a specific folder. If you need to hide it from MkDocs, you can prepend the folder with a `.`. Anyways, I usually specify some snippets folder, and then any outliers that are not in my direct path, I specify the file directly in the path:

```yaml
  - pymdownx.snippets:
      base_path:
      - docs/src/markdown/_snippets
      - LICENSE.md
      auto_append:
      - refs.txt
```

Anyways, in your case, maybe doing something like this would work:

```yaml
markdown_extensions:
  - pymdownx.snippets:
      base_path:
      - '.'
      - '../to_embed.md'
      auto_append:
      - docs/glossaire.md
```

Then you can just reference the file with `--8<-- "to_embed.md"`.  When you reference a file directly, it can be referenced with just the name, assuming it doesn't conflict with anything else.

Now, I've never actually tested much with `..`, or I don't recall testing with `..`, so I'd be interested to hear if it works.
