### DISCUSSION TITLE
How to use a GitLab CI publish the project?

### DISCUSSION THREAD

**Discussion by henrytien** [facelessuser/pymdown-extensions#1681] [Q&A] [answered]
I have watched the build.yml, it's working on GitHub, but doesn't work on GitLab, How I can change it, I have read some documents but don't achieve it, thanks. I know they are different.
```yml
name: build

on:
  push:
    branches:
      - 'main'
    tags:
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  tests:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        platform: [ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, '3.10']
        include:
          - python-version: 3.7
            tox-env: py37
          - python-version: 3.8
            tox-env: py38
          - python-version: 3.9
            tox-env: py39
          - python-version: '3.10'
            tox-env: py310
        # exclude:
        #   - platform: windows-latest
        #     python-version: 3.10

    env:
      TOXENV: ${{ matrix.tox-env }}

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      if: "!endsWith(matrix.python-version, '-dev')"
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up development Python ${{ matrix.python-version }}
      if: endsWith(matrix.python-version, '-dev')
      uses: deadsnakes/action@v1.0.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools tox coverage codecov
    - name: Test
      run: |
        python -m tox
    - name: Upload Results
      if: success()
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: ${{ matrix.platform }}-${{ matrix.tox-env }}
        fail_ci_if_error: false

  lint:
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    env:
      TOXENV: lint

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools tox
    - name: Lint
      run: |
        python -m tox

  documents:
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    env:
      TOXENV: documents

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools tox
        npm install
    - name: Install Aspell
      run: |
        sudo apt-get install aspell aspell-en
    - name: Build documents
      run: |
        npm run build
        python -m tox

```
GitLab examples for mkdocs-material.
```yml
image: python:latest
pages:
  stage: deploy
  only:
    - master 
    - main
  script:
    - pip install mkdocs-material
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
```
