### DISCUSSION TITLE
simple way to show a "source code" button?

### DISCUSSION THREAD

**Discussion by pchalasani** [facelessuser/pymdown-extensions#1762] [Q&A]
Folks, I found a few issues/discussions but cannot get the hang of it. This is the end result I am looking for: Next to a function title (or class, method, etc) there should be a "github" link or "source code" button that takes you directly to the github repo location of that function. [Optional: Even better if there is a way to refer to a specific source code line in github, as part of a doc page. ].

Is this possible with mkdocs/mkdocstrings? if so could someone point me to an example? 

I see that the docs of this repo itself have this feature: on the upper right of each doc page there is a source-link, as shown in the screenshot.
<img width="919" alt="image" src="https://user-images.githubusercontent.com/554347/180502770-0502f9d9-2990-4d25-be10-67de8b3a3d9d.png">

Would be great to know how to achieve this. Thanks!

**Comment by facelessuser** [comment]
This is all assuming the use of the MkDocs Material theme. CSS might need tweaking for other themes in MkDocs.
All of these can be acquired from the source in the documentation. Though getting the decompressed CSS built from SCSS is kind of a pain, I'm sure it can be acquired from inspecting it in the browser. But here is everything so you don't have to dig 🙂.

```markdown
[:octicons-file-code-24:][_inlinehilite]{: .source-link }

# InlineHilite
```

Below is (I think) all the CSS needed.

```css
.md-typeset a.source-link{
    position:relative;
    top:-.6rem;
    float:right;
    color:var(--md-default-fg-color--lighter);
    transition:color 125ms
}

.md-typeset a.source-link:hover{
    color:var(--md-accent-fg-color)
}

.md-typeset a.source-link .twemoji{
    height:1.2rem
}

.md-typeset a.source-link .twemoji svg{
    width:1.2rem;
    height:1.2rem
}
```

**Reply by facelessuser** [reply]
Oh, you should also be using the `attr_list` extension. MkDocs Material theme utilizes the Emoji extension to create custom emojis. You may have to manually inject the needed HTML if you aren't using MkDocs material. It's basically just a link wrapped around a specially formatted image.

**Comment by pchalasani** [comment]
Thanks
And yes I definitely use MkDocs Material.
I don’t understand anything about css so I will blindly follow these instructions :)

**Reply by facelessuser** [reply]
> I don’t understand anything about css so I will blindly follow these instructions :)

lol, understood. You should be able to copy and paste the code into a CSS file and point to it with the `extra_css` option in your `mkdocs.yml` file.

Good luck!

**Reply by facelessuser** [reply]
Make sure you've configured emoji extension as shown below:

```yaml
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
```
