### DISCUSSION TITLE
Using Mkdocs, arithmatex, and Katex

### DISCUSSION THREAD

**Discussion by bandokihiro** [facelessuser/pymdown-extensions#1953] [Q&A] [answered]
Hi!

I am trying to use the Katex backend for latex rendering within Mkdocs. I use this to generate personal notes locally. I use `mkdocs==1.4.2` and `pymdown-extensions==9.9.2`. With the following mkdocs.yml
```yaml
site_name: Katex
nav:
  - Home: index.md
      
theme:
  name: mkdocs # an other choice: readthedocs

extra_css:
  - 'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css'

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha1/contrib/auto-render.min.js'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
```
and index.md
```
# Katex

$x=2$
```
the equation doesn't render... What am I missing? Thanks! For background, I want to use Katex instead of Mathjax because I read that it supports the bm latex package.
