### DISCUSSION TITLE
Hyphenated section names don't seem possible?

### DISCUSSION THREAD

**Discussion by Midnighter** [facelessuser/pymdown-extensions#1981] [Q&A] [answered]
I was trying to include a snippet with a hyphenated section name such as

````markdown
<!-- --8<-- [start:data-ls] -->

```{bash}
ls
```

<!-- --8<-- [end:data-ls] -->
````

however, mkdocs raises an error that the snippet cannot be found. An underscore instead of a hyphen doesn't work either. This was surprising to me. Is there any way to use compound names or does it all have to be one word? `datals` works for obviously.

**Comment by facelessuser** [comment, marked as answer]
What version of Pymdown Extensions are you using?

**Reply by Midnighter** [reply]
```
pymdown-extensions          9.9.2
```

```
mkdocs                      1.4.2
mkdocs-autorefs             0.4.1
mkdocs-awesome-pages-plugin 2.8.0
mkdocs-exclude              1.0.2
mkdocs-material             9.1.2
mkdocs-material-extensions  1.1.1
mkdocstrings                0.20.0
mkdocstrings-python         0.8.3
```

Extensions config:
```yaml
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - docs/tutorials
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
```
