### DISCUSSION TITLE
Custom Scrollbar inside md-container

### DISCUSSION THREAD

**Discussion by SPyofgame** [facelessuser/pymdown-extensions#1997] [Q&A] [answered]
## Context

I want to make a custom scrollbar like this:

![image](https://user-images.githubusercontent.com/62207095/227255681-9ccca3f5-f736-4da2-af29-5caf42611574.png)

But if I move the cat, it will leave a bad gap here

![image](https://user-images.githubusercontent.com/62207095/227254918-67cf0e55-4f4b-43ed-a804-34f948ac537c.png)

I want to fill that part will color depending on the palette I am selecting (slate/light/custom). But it seems hard, so I decided to put the cat into the default scrollbar inside. Replace the default one with the cat like this

![image](https://user-images.githubusercontent.com/62207095/227254462-7f8bda0f-f296-4c4d-89d5-5ef83bec572f.png)

The problem is it somehow did not allow the webkit

![image](https://user-images.githubusercontent.com/62207095/227255525-a34e8f40-91fc-4d71-9d84-06f1fdba54e3.png)

I continue to try using gradient of colors

![image](https://user-images.githubusercontent.com/62207095/227261156-88ba392f-8cdd-4a2f-8d33-a09c6be472aa.png)

But it will depend on the size if we zoom

![Uploading image.png…]()

So I also tried to make a custom overflow with max-height like this

![image](https://user-images.githubusercontent.com/62207095/227255942-5c89a306-5994-4c27-8b3f-8b37aff2dae9.png)

but for some reason, I cant override the thumb or the track of it anymore :/

![image](https://user-images.githubusercontent.com/62207095/227256512-6490098a-5a6e-455f-a388-f1144886c5d4.png)

so I ended up having this.... 

![image](https://user-images.githubusercontent.com/62207095/227257029-348ed263-cb12-44ca-aeeb-ceaf3add9267.png)

## File CSS

```css
body::-webkit-scrollbar { 
  width: 0;
  height: 0;
  display: none;
  /* width: 30px; */
}

body::-webkit-scrollbar-track {   
  background: transparent; 
}

body::-webkit-scrollbar-thumb { 
  width: 68px;
  background-image: url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/3/cat.gif"),
    linear-gradient(
      90deg,
      transparent,
      magenta,
      red,
      yellow,
      limegreen,
      turquoise,
      blue,
      magenta,
      transparent
    );
  background-position: center bottom, center -40px;
  background-repeat: no-repeat, no-repeat;
  background-size: contain, contain;
}
    
.md-main {
  overflow-x: hidden;
  overflow-y: scroll;
  width: 100%;
  height: 100%;
  max-height: 720px;
}

.md-main::-webkit-scrollbar-track {   
  background: transparent; 
}

.md-main::-webkit-scrollbar-thumb { 
  width: 68px;
  background-image: url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/3/cat.gif"),
    linear-gradient(
      90deg,
      transparent,
      magenta,
      red,
      yellow,
      limegreen,
      turquoise,
      blue,
      magenta,
      transparent
    );
  background-position: center bottom, center -40px;
  background-repeat: no-repeat, no-repeat;
  background-size: contain, contain;
}
```
