### DISCUSSION TITLE
How to mermaid.registerIconPacks in MkDocs

### DISCUSSION THREAD

**Discussion by rmorshea** [facelessuser/pymdown-extensions#2499] [Q&A] [answered]
I can't seem to figure out how to properly register icons with mermaid as shown in [these code snippets](https://mermaid.js.org/syntax/architecture.html#icons). I just get a bunch of "?" instead of the expected icons:

![image](https://github.com/user-attachments/assets/a48254e3-74f2-4965-a76e-79380263a17c)

I attempted to add the following to my `mkdocs.yml` file:

```yml
extra_javascript:
    - https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs
    - path: js/register-mermaid-icons.js
      type: module
```

Where `js/register-mermaid-icons.js` contains:

```js
import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs";

mermaid.registerIconPacks([
    {
        name: "simple-icons",
        loader: () =>
            fetch("https://unpkg.com/@iconify-json/logos/icons.json").then((res) =>
                res.json()
            ),
    },
]);
```

I've confirmed that the JS is getting executed and that it doesn't error, but it doesn't change the outcome shown above.

My best guess is that either I'm importing a different `mermaid` than the one used by this extension or that `registerIconPacks()` is getting called after the markdown content has already been transformed into the chart.

Related question here: https://github.com/orgs/mermaid-js/discussions/5953#discussioncomment-10919748
