### DISCUSSION TITLE
Inline blocks extension syntax

### DISCUSSION THREAD

**Discussion by joapuiib** [facelessuser/pymdown-extensions#2526] [Ideas]
I've been using a lot the new block caption extensions and I love it. However, I think the block syntax could be simplified by having an "inline" syntax.

From https://github.com/squidfunk/mkdocs-material/pull/7654:

> I'm still not the biggest fan of the blocks syntax for the noise it adds, so please add this as an additional way of using figures.

Right now, captions are written with the following syntax:

```yml
- pymdownx.blocks.caption:
    auto: true
    types:
      - caption
      - name: attribution
        classes: attribution
      - name: figure-caption
        prefix: 'Figura {}.'
```

```md
![img](placeholder.png)
/// attribution
Unknown author
///
/// figure-caption | < ^1
Caption
///
```

With inline syntax, could become:

```md
![img](placeholder.png)
/// attribution: Unknown author
/// figure-caption | < ^1 : Caption
```

This is just a consideration about the block syntax and an idea of how it could be improved. I know "inline" syntax would increase complexity a lot.
