### DISCUSSION TITLE
Can you auto-append snippets only for specific pages/directories?

### DISCUSSION THREAD

**Discussion by Andre601** [facelessuser/pymdown-extensions#2530] [Q&A] [answered]
I was wondering if it was possible to make the snippet extension only auto-append snippets for specific file/folder paths?

If not, could it be considered? For example like this:
```yaml
markdown_extensions:
  - pymdownx.snippets:
      auto_append: ['footnotes.md']
      auto_append_paths: ['posts/*'] # Would only auto-append to files inside the 'posts' folder.
```
