### DISCUSSION TITLE
[Highlight] Applying additional pygments highlighters

### DISCUSSION THREAD

**Discussion by Andre601** [facelessuser/pymdown-extensions#2607] [Q&A] [answered]
Was wondering if there are any additional steps required for adding additional syntax highlighters in pygments, or if it just requires installing the highlighter via `pip install` and then use the matching identifier for the fenced code block.

I ask, because I did exactly that. I've installed the lexer in question and applied the identifier to the code block, yet it doesn't apply the proper highlighting to the block, making me wonder if there are any additional steps required.

I use pymdownx.highlight as an extension for MkDocs (with Material for MkDocs theme), if that is of any importance.

**Comment by facelessuser** [comment, marked as answer]
This project uses custom highlighters, well only one, but it's from here: https://github.com/facelessuser/pymdown-lexers. See results here https://facelessuser.github.io/pymdown-extensions/extensions/critic/.

There is no additional setup, see MkDocs config: https://github.com/facelessuser/pymdown-extensions/blob/main/mkdocs.yml.

**Reply by Andre601** [reply]
Okay. This makes it even more confusing then, because as I mentioned is the highlighting not working, despite using the right identifier and having the pygment lexxer installed.

Tho, looking at your config, I can see you actually do have some modifications, even if unrelated, so maybe not the best example? 😅 

Maybe I need to make some setting changes in SuperFences? 🤔

**Reply by facelessuser** [reply]
Yes, but none of the modifications have anything to do with the critic highlighting.

**Reply by Andre601** [reply]
True.

Would you have any idea what else could cause such problem on my end?
I doubt it's something like a conflicting extension. I'm not using the Python Markdown highlighter or any other extension that does code block stuff. And other code block langs like YAML work fine.

Just in case is here the full extension list and their settings used:
```yaml
markdown_extensions:
  - markdown.extensions.toc:
      permalink: true
      toc_depth: 3
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
  - pymdownx.magiclink:
  - pymdownx.superfences:
  - pymdownx.snippets:
      base_path: docs/.snippets
      auto_append:
        - links.md
  - pymdownx.blocks.admonition:
      types:
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.blocks.details:
  - pymdownx.caret:
```

**Reply by Andre601** [reply]
I've deployed it to the actual docs and there does it work fine...
So this seems to yet again be the issue I encountered with making my own lexer, which is that it won't render locally, but will remotely...

Not sure if it is due to some env variable or a difference in the OS (Production is build through Actions with Ubuntu) that causes this... 🤔

**Reply by facelessuser** [reply]
I have no idea what you are doing. Like I said, I have an example project that works and is integrated directly into this documentation. I also use that same package in other projects using the color highlighter that highlights color syntax: https://facelessuser.github.io/coloraide/colors/srgb/#inputoutput.

It's all working. Are you installing it as a pip package or trying to run from a local folder? I pip install mine and it uses the entry points to be seen as a registered lexer.

I could throw together a very simple example project that demonstrates it working without any other extensions...

**Reply by facelessuser** [reply]
@Andre601 Here's a most basic example. Assuming the custom lexer is installed:

```console
python3 -m pip install git+https://github.com/facelessuser/pymdown-lexers.git
```

Config:

```yaml
site_name: My Docs

theme:
  name: material

markdown_extensions:
- pymdownx.superfences:
```

Index.md

````markdown
# Welcome to MkDocs

```critic-markup title="Critic Markup Accept"
Here is some {--*incorrect*--} Markdown.  I am adding this{++ here++}.  Here is some more {--text
 that I am removing--}text.  And here is even more {++text that I 
 am ++}adding.{~~

~>  ~~}Paragraph was deleted and replaced with some spaces.{~~  ~>

~~}Spaces were removed and a paragraph was added.

And here is a comment on {==some
 text==}{>>This works quite well. I just wanted to comment on it.<<}. Substitutions {~~is~>are~~} great!

General block handling.

{--

* test remove
* test remove
* test remove
    * test remove
* test remove

--}

{++

* test add
* test add
* test add
    * test add
* test add

++}
```
````

Results

<img width="1023" alt="Screenshot 2025-02-16 at 3 53 23 PM" src="https://github.com/user-attachments/assets/cc152ede-60a5-487b-89ef-ffc2f26fa166" />

All I can say is that if you do exactly what I do in mine, it works.

I unfortunately don't have time to debug other people's projects.
