### DISCUSSION TITLE
How to use collapse-code in `tools` of this repo?

### DISCUSSION THREAD

**Discussion by RonaldLN** [facelessuser/pymdown-extensions#2638] [Q&A] [answered]
When I read the docs of this repo, I notice things like at the bottom of this page

https://facelessuser.github.io/pymdown-extensions/extensions/details/

the code block can be collapsed and only show several lines.

Then I look the source markdown file, and found

```
//// collapse-code
...
////
```

then I look the mkdocs.yml

```yaml
markdown_extensions:
  - tools.collapse_code:
      expand_text: ''
      collapse_text: ''
```

then, I try to add this thing to my docs. I copy the whole diretory `tools` and add same `tools.collapse_code: ...` lines in my `mkdocs.yml`, but get error when `mkdocs serve`.

can some one tell me how to add this things correctly? I think this looks very nice and I really want to use it in my docs.

Thanks!
