### ISSUE TITLE
Highlight: CSS lexer does not recognize "modern" operators and functions

### ISSUE THREAD

**Issue by martinbira** [facelessuser/pymdown-extensions#1067]
Modern operators and functions in CSS, such as `@media`, `:root`, and `::part` are not recognized as whole parts but as a combination of punctuation followed by the operator or function, e.g. `@` and `media`, `:` and `root`, and `::` and `part`.

## Expected behaviour
"Modern" CSS operators and functions should be highligted as such.

## Actual behaviour
"Modern" CSS operators and functions are separeted into different parts. 

## Steps to reproduce
On a MkDocs site utilising PyMdown Extensions Highlight add the following code snippet styled as css to a page:
``` css
:root {
  --md-primary-fg-color--dark: #90030C;
}

::part(breadcrumbs) {
  font-size: 14px;
}

@media only screen and (max-width: 800px) {
  .md-typeset a{color: var(--md-primary-fg-color--dark);}
}
``` 

View result.
