### ISSUE TITLE
Failed loading extension "pymdownx.magiclint"

### ISSUE THREAD

**Issue by redtux** [facelessuser/pymdown-extensions#1099]
Hi, I am having troubles using `pymdownx.magiclint`.

As I found no corresponding bug reports, it might simply be a user issue concerning wrong configuration.

In my `mkdocs.yml` I have the following section:

```yaml
markdown_extensions:
  - pymdownx.magiclint:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      provider: 'github'
      user: 'myuser'
      repo: 'myrepo'
```

When running `mkdocs serve` I get the following error:

```sh
INFO    -  Building documentation... 
ERROR   -  Config value: 'markdown_extensions'. Error: Failed loading extension "pymdownx.magiclint". 

Aborted with 1 Configuration Errors!
```

Without using `pymdownx.magiclint` everything works fine. With the above section, it is not working. I have no issues with other PyMdown extensions. Just like you I am using `mkdocs-material` (5.5.13).

I followed the [FAQ](https://facelessuser.github.io/pymdown-extensions/faq/#github-ish-configurations) and the [MagicLink](https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/#options) documentation, and cross-checked with this project's [`mkdocs.yml`](https://github.com/facelessuser/pymdown-extensions/blob/master/mkdocs.yml) file. Am I missing something?

```sh
pip --version
pip 20.2.3 from /home/redtux/.local/lib/python3.8/site-packages/pip (python 3.8)
```

```sh
mkdocs --version
mkdocs, version 1.1.2 from /home/redtux/.local/lib/python3.8/site-packages/mkdocs (Python 3.8)
```

```sh
pip show pymdown-extensions | egrep 'Version|Location'
Version: 8.0
Location: /home/redtux/.local/lib/python3.8/site-packages
```

Thank you for your help and for those great extensions! :heart:
