### ISSUE TITLE
Tabbed: support printing tabbed content

### ISSUE THREAD

**Issue by timvink** [facelessuser/pymdown-extensions#1112]
First of all, awesome plugin! Thanks for all the effort that has gone in!

I'm developing a plugin to help print mkdocs sites to PDF via the browser. I noticed the tabbed content only shows one of the tabs:

From: https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
File > Print > Preview

![image](https://user-images.githubusercontent.com/5570380/94807912-93b3ca80-03f0-11eb-928a-4db1d98f53a5.png)

You give some guidance on how to style via CSS here:
https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/#styling-with-css

Is is possible to describe how to print all tabs by displaying them all underneath each other? Some thing like

```css
@print {
.tabbed-set {
  display: inline-block;
}
}
```
?

Or should there be some javascript to support this?

**Comment by facelessuser** [comment]
@timvink probably:

```css
.tabbed-content {
    display: block !important;
}
```

This is really something a theme should do though. We just spit out the content, it's up to the use to style in the way best suited for their needs.
