### ISSUE TITLE
SuperFences line numbers not aligned with the fence block

### ISSUE THREAD

**Issue by Maxiride** [facelessuser/pymdown-extensions#112]
With the following code (\ added to not parse the closing backticks) the fence that get generated has the line numbers misaligned with the block like in the attached screenshot.

![image](https://user-images.githubusercontent.com/3630857/30386110-52a1dfba-98a9-11e7-9cd4-de71cf809547.png)

```
```php linenums="15"
// Add you bot's API key and name
$bot_api_key  = 'your:bot_api_key';
$bot_username = 'username_bot';
\```
```

I didn't managed to find a solution yet.

**Comment by facelessuser** [comment]
>  (\ added to not parse the closing backticks)

This is unnecessary.  If you want to show backticks in a code block, just make sure the outer backticks have 1 greater than what you want to show in the inner:

`````
````
```
code
```
````
`````

Most likely something is setup wrong in your project.  Without more details, I am afraid I won't be able to guess.  As you can see, it works fine in my documents using the latest mkdocs, mkdocs-material, markdown, and pymdown-extensions:

![2017-09-13 09_43_56-superfences - pymdown extensions documentation](https://user-images.githubusercontent.com/1055125/30387025-94a9d642-9868-11e7-936c-de95f00aa83d.png)

**Comment by Maxiride** [comment]
Which infos can I provide to help debugging this issue of mine?

This is my mkdocs.yml if it helps.
```yml
# Site infos
site_name: 'PHP Telegram Bot Documentation'
pages:
    - Home: index.md
    - About: about.md
    - Code Playground: test.md


# Theme and its options
#https://squidfunk.github.io/mkdocs-material/
theme: 'material'
extra:
  palette:
    primary: 'blue'
    accent: 'cyan'
  feature:
    tabs: false

# Extensions with reference url
markdown_extensions:
    - smarty

    - admonition

    #https://pythonhosted.org/Markdown/extensions/abbreviations.html
    - abbr

    #https://pythonhosted.org/Markdown/extensions/definition_lists.html
    - def_list

    #https://pythonhosted.org/Markdown/extensions/footnotes.html
    - footnotes

    #https://facelessuser.github.io/pymdown-extensions/
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png

    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.snippets
    - pymdownx.highlight

```
