### ISSUE TITLE
Highlight custom parameteres - Shell

### ISSUE THREAD

**Issue by Maxiride** [facelessuser/pymdown-extensions#113]
I think I haven't fully understood how to implement custom names for highlighting code.
I've added in the mkdcos.yml:

```
- pymdownx.highlight:
        css_class: codehilite
        extend_pygments_lang:
          - name: php
            lang: php
            options:
              startinline: true
          - name: shell
            lang: console
            options:
              startinline: true
```

With the Pygments demo I ensured that the highlight I want is the [Bash Session](http://pygments.org/demo/6641310/), and from the docs I checked the [valid names](http://pygments.org/docs/lexers/#lexers-for-various-shells) however when creating the SuperFence

````
```shell
$ vagrant init ubuntu/xenial64
```
````

no highlights is applied.

**Comment by facelessuser** [comment]
I'm not really sure what you are doing.  is `startinline` a valid option for shell? I don't think it is.  I guess you are trying to override shell with the console language? Instead of the default shell?

**Comment by facelessuser** [comment]
Okay.  I took a look:

1.  I don't think you can use the `startinline` is a valid option.  Only certain languages have additional options, and they will be listed under the associated lexer at http://pygments.org/docs/lexers/.  Check out PHP and you'll see what I mean.

2. When I did the following, it worked as expected:
 
    ```
      - pymdownx.highlight:
          css_class: codehilite
          extend_pygments_lang:
            - name: php-inline
              lang: php
              options:
                startinline: true
            - name: shell
              lang: console
    ```

    I imagine you are expecting the dollar sign to be highlighted, but depending on the color scheme used, this might not be the case.  With the color scheme provided by Material, the dollar sign does not get highlighted, but it is properly scoped with `gp`. The first code block was done with shell mapped to console, the second is console directly:

    ![screenshot 2017-09-17 15 10 51](https://user-images.githubusercontent.com/1055125/30524948-80a8fc40-9bba-11e7-9821-55ec863d515c.png)
