### ISSUE TITLE
PHP variables are not colored

### ISSUE THREAD

**Issue by timgavin** [facelessuser/pymdown-extensions#1140]
I have followed the instructions and example on the [Extended Pygments Lexer Options](https://facelessuser.github.io/pymdown-extensions/extensions/highlight/#extended-pygments-lexer-options) page, yet my PHP variables remain gray, while in the example they are colored.

I'm using MkDocs with the Material theme. Is this a bug, or am I missing something?

#### mkdocs.yaml

```
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: true
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
```

#### The markdown (indented to show fences)

```
    ```php-inline
    $a = array("foo" => 0, "bar" => 1);
    foreach($a as $key => $value) {
        // comment
        echo "{$key} => {$value}"
    }
    ```
    
    `#!php-inline $a = array("foo" => 0, "bar" => 1);`
```

#### Result

<img width="361" alt="Screen Shot 2020-11-02 at 8 05 54 AM" src="https://user-images.githubusercontent.com/1012049/97890338-48882280-1ce2-11eb-8862-10dd3b482af8.png">
