### ISSUE TITLE
Should I see ::before icons for links created by magiclink?

### ISSUE THREAD

**Issue by clintval** [facelessuser/pymdown-extensions#1240]
I love the icons you have that prefix magiclinks and would like the same on my site!

I have not been able to get them to render and before I spend any more time debugging, I wanted to confirm that I _should_ expect to see them and they are not simply custom styling on your documentation repository:

Here is what I am expecting:

<img width="400" alt="Screen Shot 2021-02-15 at 11 43 06 AM" src="https://user-images.githubusercontent.com/4634699/107973354-22ca1500-6f83-11eb-886e-d44e855f5985.png">

But when I paste that same Markdown into my site I see:

<img width="396" alt="Screen Shot 2021-02-15 at 11 44 52 AM" src="https://user-images.githubusercontent.com/4634699/107973474-3e352000-6f83-11eb-92b1-1bbe2e7a6082.png">

Here is the relevant part of my site configuration:

```yaml
markdown_extensions:
  ...
  - pymdownx.magiclink:
      provider: github
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
```
