### ISSUE TITLE
Add snippet to all files in a folder (snippet or abbr feature ?)

### ISSUE THREAD

**Issue by MithrilMan** [facelessuser/pymdown-extensions#1285]
Hello, first of all thanks for your extensions, I just started looking into mkdocs and I found them really useful.
Having said that, I'd like to know if it's possible to include a snippet in all files in a folder, because I like to use it for abbr plugin but adding the snippet to each file is tedious and I may even forget to add it.

when I say folder, I mean maybe using a pattern, something like this

```
markdown_extensions:
  - abbr
  - pymdownx.snippets:
      base_path: doc/_snippets
      append:
         source: abbr.txt
         destination:
          - myfolder/*.md
          - another-folder/*.md
```

what I'm proposing is **append** configuration parameter

I understand that the problem is that a snippet can be placed everywhere but, at least in my case, I use it for links and abbr referenecs, so it really fits well the "append" concept, where you basically append the snippet at the end of each file

another approach I could maybe suggest is add an attribute to specify to append the snippet, so I can add the snppet syntax on the top of the document (wher I usually place meta data information since I'm using mkdocs-material <https://squidfunk.github.io/mkdocs-material/reference/meta-tags/> )

something like `--8<-- "refs.txt" [append] `

probably this concept would stick more to the abbr plugin but I suppose it make sense for snippets too?

I'm not into python and mkdocs so I can't spend time to do that myself, that's why I'm posting this otherwise I would have issued a PR :)
thanks

P.S.
I see it may be useful to your repo too because you manually added refs to many of your pages 😛

**Comment by facelessuser** [comment]
I am actually already working on this feature, but it will look different than described:

```yaml
markdown_extensions:
  - abbr
  - pymdownx.snippets:
      base_path: doc/_snippets
      auto_append:
      - abbr.txt
```

All mentioned files in `auto_append` would be appended to every file. Files are resolved relative to the `base_path`.

I'm not currently planning a `destination` option as destinations are a MkDocs thing, not a Python Markdown. Python Markdown doesn't work on a file, so no file name is known. It works on a buffer that has no name.
