### ISSUE TITLE
[Question] How to use language/syntax from plugins in admonitions?

### ISSUE THREAD

**Issue by eltbus** [facelessuser/pymdown-extensions#1325]
With markdown-katex I can normally start a math code block as follows:
````
```math
\dot x = x
```
````

However, wrapping that block inside an admonition fails to interpret "math" as a language, and the formulas are not rendered.

Could anyone provide a generic example of how to add other languages to superfences?

**Comment by facelessuser** [comment]
Without seeing what plugins you are using and how they are configured, it is difficult to understand what you are doing wrong.

Can you post a minimal example illustrating your issue?

**Comment by facelessuser** [comment]
Additionally, you mention it doesn't work in admonitions, but I don't even see how you are using them in admonition. In the past I've seen misunderstandings from people on how content should be placed in admonitions, so there is a lot of unknowns here without seeing a full minimal example.

**Comment by eltbus** [comment]
Hi @facelessuser, thank you for your time. This is should be a minimal example:

I'm using the following packages:

```
[packages]
mkdocs = "*"
mkdocs-material = "*"
mkdocs-material-extensions = "*"
markdown-katex = "*"
```

A minimal mkdocs.yml:
```yaml
site_name: test-katex
nav:
    - Home: index.md
################################################################################
theme:
    name: material
    features:
        - navigation.instant
markdown_extensions:
    - markdown_katex:
        no_inline_svg: True
        insert_fonts_css: True
    - admonition
    - pymdownx.details
    - pymdownx.tabbed
    - pymdownx.superfences
```

And a sample index.md
````
```math
y' = f(x) \longrightarrow y(x) = \int f(x)dx + C
```

!!! danger
    ```math
    y' = f(x) \longrightarrow y(x) = \int f(x)dx + C
    ```

??? example "Collapsible"
    ```math
    y' = f(x) \longrightarrow y(x) = \int f(x)dx + C
    ```

=== "Pymdownx tabs"
    ```math
    y' = f(x) \longrightarrow y(x) = \int f(x)dx + C
    ```

=== "Another tab"
    ```math
    y' = f(x) \longrightarrow y(x) = \int f(x)dx + C
    ```
````

When I run mkdocs serve, I get a page looking kinda like this:
![pic-selected-210504-1551-58](https://user-images.githubusercontent.com/33374178/117014058-b7c1ec00-acf0-11eb-9fc4-66904e87ad73.png)
