### ISSUE TITLE
Question: How to properly include code blocks inside details?

### ISSUE THREAD

**Issue by makshh** [facelessuser/pymdown-extensions#136]
I'm using Material for MkDocs 2.0.4 and I would like to put code block inside `details`.

### First input (4 spaces - no code block)

````
??? summary "Summary"

    ```
    <p>Paragraph</p>
    ```
````

![screenshot at nov 07 23-27-35](https://user-images.githubusercontent.com/5025950/32521298-43c09cd0-c413-11e7-9962-f7bdece4bc0b.png)

### Second input (8 spaces - code block with ``` and no styling)

````
??? summary "Summary"

     ```
     <p>Paragraph</p>
     ```
````
![screenshot at nov 07 23-27-17](https://user-images.githubusercontent.com/5025950/32521301-4702b75c-c413-11e7-81b1-758dd0d5baf3.png)

EDIT: I see that it's working on [your site](https://facelessuser.github.io/pymdown-extensions/extensions/details/#browser-support), I checked raw file and I think I'm doing it properly.

My extensions

```
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.mark
```
