### ISSUE TITLE
Details + Tabbed + Superfences misbehaving when using spaces and not tabs

### ISSUE THREAD

**Issue by perezd** [facelessuser/pymdown-extensions#1628]
### Description

Given the following combination of markdown syntax:

```
???+ "Neutral Summary w/ Multi-Code"
  Also some text.

  === "Bash Stuff"
    ```bash
    #!/bin/bash
    STR="Hello World!"
    echo $STR
    ```
```

I see something like this:
![Screen Shot 2022-03-06 at 6 32 55 PM](https://user-images.githubusercontent.com/20598/156957916-757ee358-4d5f-4ca4-8eb1-bad79169e76d.png)

This works as expected, however the file in question is using tabs and not spaces. If I switch to spaces, I see this:
![Screen Shot 2022-03-06 at 6 33 53 PM](https://user-images.githubusercontent.com/20598/156958074-bbdd3161-ced8-4a19-8313-c947eb0bc99a.png)

Is this a specific limitation of the tool? I'm exercising these features using MkDocs.
Individual components seem to work, it really seems like the introduction of details + tabbed causes an unexpected outcome.



### Minimal Reproduction

1. write the snippet above as tabs.
2. Use "convert to spaces" in VSCode.

### Version(s) & System Info

- Operating System: MacOS (M1) Monterey 12.2.1
- Python Version: 3.9.10
- Package Version: 9.2

**Comment by limbic-derek** [comment]
Also, here is all my extension configs:

```
markdown_extensions:
  - markdown.extensions.attr_list:
  - markdown.extensions.wikilinks:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.details:
  - pymdownx.highlight:
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
      custom_fences:
        - name: diagram
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
  - pymdownx.snippets:
      check_paths: true
      base_path: 'pages/'
  ```

I should mention this markdown is nested within an HTML block as well.

```
<r-cell markdown="block" span=row>
  <!-- markdown is here -->
</r-cell>
```
