### ISSUE TITLE
Copy to clipboard button in code blocks

### ISSUE THREAD

**Issue by Dzeri96** [facelessuser/pymdown-extensions#1844]
### Description

I was recently looking into adding "copy to clipboard" button to my [Pelican](https://getpelican.com/) blog and there seem to be a few ways to do this, with the most common one being a script that injects these elements when loaded (like in the docs of this project). One could go one level deeper and write a Pelican plugin, but since the `Highlight` extension provides a lot of ways to customize code blocks, I was thinking we could maybe add this functionality to it.

### Benefits

Adding this button at "compile-time" would improve loading times of these pages, however, if the user has JS disabled, these buttons would be useless.

### Solution Idea

I'm not sure if injecting JS is in the scope of this plugin, so this feature might be infeasible, however, we could solve the _useless button_ problem by assigning a css class to these elements that hides them by default, and then JS would change the CSS dynamically when loaded.

**Comment by Dzeri96** [comment]
Alright, that's fair. I'm using SuperFences but I haven't looked too much into all of the features it has. You're saying I could use it to add such a button?

**Comment by facelessuser** [comment]
Yes, this should be possible.

**Comment by Dzeri96** [comment]
Then I guess we can close this issue.

**Comment by facelessuser** [comment]
You might find this helpful: https://github.com/facelessuser/pymdown-extensions/discussions/1739#discussioncomment-3019558. If you are doing this for all languages, you might just try and override `*` which should make your custom fence the default. Anyways, hopefully this helps.

**Comment by Kristinita** [comment]
### 1. Reason for re-opening issue

In recent years, I’ve often seen clipboard buttons inside code blocks. Among other sites, we can see the clipboard buttons:

1. Here in GitHub Issues
1. [**In the SuperFences documentation**](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/)

Since, in my opinion, clipboard buttons is a common feature, it would be nice to be able to add it through options.

### 2. MCVE

#### 2.1. KiraCodeBlock.md

````md
```text
Kira Goddess!
```

````

#### 2.2. Command

```text
python -m markdown -x pymdownx.superfences KiraCodeBlock.md
```

#### 2.3. Output

```html
<!-- [QUESTION] What needs to be done to prevent blank “<span></span>” from being generated? -->
<div class="highlight"><pre><span></span><code>Kira Goddess!
</code></pre></div>
```

### 3. Example of expected behavior

#### 3.1. Configuration

```yaml
pymdownx.superfences:
  # [INFO] For my real clipboard buttons I use Clipboard.js and Balloon.css
  # and needs this markup:
    clipboard_button: '<button class="SashaClipboardButton" data-balloon-pos="left"
      aria-label="Copy the contents of this block"><img class="SashaClipboardImage"
      src="https://kristinita.netlify.app/theme/images/interface-images/clippy.svg"
      alt="Clipboard button" loading="lazy"></button>'
```

#### 3.2. Expected output

```html
<!-- [INFO] Insert the “clipboard_button” content between “<pre>” and “<code>” -->
<div class="highlight"><pre><button class="SashaClipboardButton" data-balloon-pos="left" aria-label="Copy the contents of this block"><img class="SashaClipboardImage" src="https://kristinita.netlify.app/theme/images/interface-images/clippy.svg" alt="Clipboard button" loading="lazy"></button><code>Kira Goddess!
</code></pre></div>
```

Thanks.
