### ISSUE TITLE
Math content padding incorrectly with latest Material theme

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/pymdown-extensions#187]
Need to regen with Material 2.2.0 as current documentation is messed up.  Last known good version is 2.2.0. This is pre-admonition/details fixes.

Extra padding with nested details/admonitions. Though 2.2.2 seems to fix this, it also adds `overflow: auto` which can make scroll bars appear in weird cases.

<img width="664" alt="details" src="https://user-images.githubusercontent.com/1055125/33785646-385da55e-dc23-11e7-841e-834d0f0afc8a.png">

Math getting cut off.  This gets cut off in both 2.2.1 and 2.2.2.

<img width="668" alt="arithmatex" src="https://user-images.githubusercontent.com/1055125/33785656-3fa6775a-dc23-11e7-8a57-179543f450af.png">

@squidfunk, just an FYI.  I'll create an issue over on Material once I have time to look into this more.

**Comment by facelessuser** [comment]
Seems the padding on the last child is causing the issue, I just don't understand why yet.

```css
html .md-typeset .admonition :last-child, html .md-typeset details :last-child {
    margin-bottom: 0;
    padding-bottom: 1.2rem;
}
```
