### ISSUE TITLE
markdownextradata-plugin variables don't get resolved in Snippets

### ISSUE THREAD

**Issue by Stwissel** [facelessuser/pymdown-extensions#1952]
### Description

When using Snippets embedded variables `{{ somename }}` from the [mkdocs-markdownextradata-plugin](https://github.com/rosscdh/mkdocs-markdownextradata-plugin) don't get resolved. Calling the snippet page directly shows resolution. This is cross-posted [from here](https://github.com/rosscdh/mkdocs-markdownextradata-plugin/issues/45).

Love your work!

### Minimal Reproduction

I'm using your nice plugin together with the `pymdownx.snippets` plugin

## I have

```yaml
extra:
  test: 1.0.0
plugins:
  - search
  - awesome-pages
  - section-index
  - tags
  - markdownextradata
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      base_path:
        - "docs/snippets"
```

and a `test.md`

```md
# Test of extras

This is top: {{test}}

--8<-- "snippet.md"

End
```

and a `snippet.md`

```md
In the snippet: {{test}}
```

## Expected outcome

```html
<h1>Test of extras</h1>

This is top: 1.0.0
In the snippet: 1.0.0

End
```

## Actual outcome

```html
<h1>Test of extras</h1>

This is top: 1.0.0
In the snippet: {{test}}

End
```

What do I miss?

### Version(s) & System Info

- Operating System: Linux container, Kernel 5.15.78-0-virt, Alpine Linux v3.15 
- Python Version: 3.11.0
- Package Version: 9.9
