### ISSUE TITLE
Custom fence breaks other fences?

### ISSUE THREAD

**Issue by guillevg** [facelessuser/pymdown-extensions#2069]
### Description

I am trying to create a custom fence for `<figcaption>`. It kind of works, but:

1. Adds the `<figure>` block inside a `<p>` with text *None*.
2. Breaks `py` and `mermaid` fences. They work well if there is no `figcaption` fence in the source. Otherwise, they get converted to a `<p><code>` block.

This is my custom fence code (I run `python -m mkdocs serve` so that it finds it, as I saw in #928):

```python
def fence_figcaption_format(source, language, class_name, options, md, **kwargs):             
    """Format source as figcaption."""                                                        
    caption, mkd = source.strip().split('\n')
    return '<figure>%s<figcaption>%s</figcaption></figure>' % (md.convert(mkd), caption)
```

This is my markdown:

<pre>
```py
def func(a, b):
    pass
``` 

```figcaption
CAPTION
![ALT_TEXT](https://dummyimage.com/600x400/adadad/fff)
```
</pre>

This is the final HTML:

```html
<p><code>py
def func(a, b):
    pass</code></p>
<p>None<figure><p><img alt="ALT_TEXT" src="https://dummyimage.com/600x400/adadad/fff" /></p><figcaption>CAPTION</figcaption></figure></p>
```

My `mkdocs.yml` extensions section:

```yaml
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details                                                                          
  - markdown.extensions.smarty                                                                
  - markdown.extensions.sane_lists                                                            
  - pymdownx.highlight:                                                                       
      anchor_linenums: true                                                                   
      line_spans: __span                                                                      
      pygments_lang_class: true                                                               
  - pymdownx.inlinehilite                                                                     
  - pymdownx.snippets                                                                         
  - pymdownx.superfences:                                                                     
      custom_fences:                                                                          
        - name: mermaid                                                                       
          class: mermaid                                                                      
          format: !!python/name:pymdownx.superfences.fence_code_format                        
        - name: figcaption                                                                    
          class: figcaption                                                                   
          format: !!python/name:lib.custom_fences.fence_figcaption_format                     
  - footnotes                                                                                 
  - abbr                                                                                      
  - attr_list                                                                                 
  - pymdownx.emoji:                                                                           
      emoji_index: !!python/name:materialx.emoji.twemoji                                      
      emoji_generator: !!python/name:materialx.emoji.to_svg                                   
  - md_in_html
```

Thank you.

### Minimal Reproduction

Just set up as above.

### Version(s) & System Info

- Operating System: Pop!_OS 22.04 LTS
- Python Version: 3.10.6
- Package Version: 10.0.1
