### ISSUE TITLE
extend_pygments_lang doesn't work for C/C++

### ISSUE THREAD

**Issue by Mefiresu** [facelessuser/pymdown-extensions#2447]
### Description

Using an option like `c99highlighting` breaks code highlighting.
Tested with the [PHP example](https://facelessuser.github.io/pymdown-extensions/extensions/highlight/#extended-pygments-lexer-options) and this one works fine.

![image](https://github.com/user-attachments/assets/d01cac05-9fbf-4166-8c26-4e966415c840)

Using mkdocs-material here, but it breaks with the base mkdocs theme as well.

Pygments seems to be working correctly as a CLI tool and outputs correct html:
```html
<div class="highlight">
  <pre>
    <span></span><span class="n">int32_t</span><span class="w"> </span><span class="nf">foobar</span><span class="p">(</span><span class="kt">unsigned</span><span class="w"> </span><span class="kt">int</span><span class="w"> </span><span class="n">x</span><span class="p">,</span><span class="w"> </span><span class="n">uint16_t</span><span class="w"> </span><span class="n">y</span><span class="p">);</span>
  </pre>
</div>
```

### Minimal Reproduction

mkdocs.yml config:
```yaml
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
    extend_pygments_lang:
      - name: c-noc99
        lang: c
        options:
          - c99highlighting: false
```

C code block:
````md

```c-noc99
int32_t foobar(unsigned int x, uint16_t y);
```
````

### Version(s) & System Info

- Operating System: Arch Linux (6.10.7-zen1-1-zen kernel)
- Python Version: Python 3.12.5
- Package Version: 10.9
