### ISSUE TITLE
pymdownx.hightlight seems to not get picked up

### ISSUE THREAD

**Issue by matthias-Q** [facelessuser/pymdown-extensions#2645]
### Description

Hi, 
I am trying to convert a md with sql into html. The HTML block is fenced.
I would expect that the resulting html would have `class="language-sql linenums"` when only using `pymdownx.highlight`. It looks like pymdownx.highlight is not used at all.

My env is managed using uv. See the Pyproject.toml below.

### Minimal Reproduction

```python
import markdown

md_text = """
```sql
select * from table;
```"""

html = markdown.markdown(
    md_text,
    extensions=[
        'pymdownx.highlight',
        'fenced_code',
    ],
    extension_configs={
        'pymdownx.highlight': {
            'linenums': True,
        }
    }
)

assert """<pre><code class="language-sql linenums">select * from table;
</code></pre>""" == html
```
With `fenced_code` I get:
```html
<pre><code class="language-sql">select * from table;
</code></pre>
```

Without `fenced_code` I only get
```html
<p><code>sql
select * from table;</code></p>
```

### Version(s) & System Info

- Operating System: Linux
- Python Version: 3.13

```toml
[project]
name = "glpages"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "markdown>=3.7",
    "pygments>=2.19.1",
    "pymdown-extensions>=10.14.3",
]
```

Cross check:
```
uv run python -c "import pymdownx;print(pymdownx.__version__)"
10.14.3
```
