### ISSUE TITLE
Nested tabs in the unofficial "steps extension" stopped working in 10.14

### ISSUE THREAD

**Issue by hellt** [facelessuser/pymdown-extensions#2650]
### Description

I have been using the CSS trick to enable the Steps functionality as linked [here](https://github.com/squidfunk/mkdocs-material/issues/7760#issuecomment-2574390090).

To be precise, the steps functionality has been copied verbatim, and added to the mkdocs-material via extra css:

```css
:root>* {
    --md-steps-bg-color: var(--md-code-bg-color);
    --md-steps-fg-color: var(--md-code-fg-color);
    --md-steps-border-color: hsla(0, 0%, 75%, 1);
}

:root>*[data-md-color-scheme="slate"] {
    --md-steps-border-color: hsla(225, 15%, 30%, 1);
}

.md-typeset div.steps>ol {
    counter-reset: item;
}

.md-typeset div.steps>ol>li {
    position: relative;
    padding-left: 1em;
    list-style: none;
}

.md-typeset div.steps>ol>li::before {
    position: absolute;
    top: 0;
    left: 0;
    z-index: -1;
    display: block;
    width: 1.75em;
    height: 1.75em;
    margin-left: -1.25em;
    color: var(--md-steps-fg-color);
    font-weight: 600;
    font-size: 0.9em;
    text-align: center;
    background-color: var(--md-steps-bg-color);
    border: 1px solid var(--md-steps-border-color);
    border-radius: 100px;
    content: counter(item);
    counter-increment: item;
}

.md-typeset div.steps>ol>li::after {
    position: absolute;
    top: 0;
    bottom: 0;
    left: -0.36em;
    display: block;
    width: 1px;
    margin-top: 2em;
    border-left: 1px solid var(--md-steps-border-color);
    content: '';
}
```

After upgrading to 10.14 from 10.12 I noticed that nesting tabs under the "step" stopped working.

It used to be rendered like this with 10.12:

![Image](https://github.com/user-attachments/assets/e69e7649-801f-4417-b11f-87cca3556305)

And after upgrading to 10.14.3 the second tab started to be placed outside of the step:

![Image](https://github.com/user-attachments/assets/700696d3-7abe-4c4c-bf33-2747d291deec)

My blocks config:

```yaml
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.blocks.html:
      custom:
        - tag: td
          mode: block
        - tag: th
          mode: block
```

### Minimal Reproduction

1. Add steps.css as listed above
2. create a steps markdown file like below:

```
/// html | div.steps

1. Step1

    //// tab | First tab
    ////
    //// tab | Second tab
    ////
///
```
3. Observe that the second tab is rendered outside of the step.

### Version(s) & System Info

- Operating System: Debian 12
- Python Version: 3.11
- Package Version: 10.14.3
