### ISSUE TITLE
Snippets are not reliably rendering

### ISSUE THREAD

**Issue by tonglil** [facelessuser/pymdown-extensions#530]
## Description

Unable to get Snippets to include a file consistently after using it in a tabbed superfence.

My guess is some issue w/ superfences?

Nothing in usage notes mentions snippets + superfences incompatibility? https://facelessuser.github.io/pymdown-extensions/usage_notes/

### Expected behavior

Trying to render README.md:

<pre>

# Test

## Section 1

Why do these non-inline sections work (but same code does not work below)?

```yaml
--8<--
snip/test.yaml
--8<--
```

```yaml
--8<--
snip/test.yaml
--8<--
```

Complex inline tabbed superfences work:

```yaml tab="Ok"
--8<-- "snip/test.yaml"
```

```yaml tab="Ok 2"
--8<-- "snip/test.yaml"
```

```yaml tab="Same non-inlined code from above is not ok"
--8<--
snip/test.yaml
--8<--
```

Now it doesn't work?

--8<--

snip/test.yaml

--8<--

## Ok section

Seems like only inline works..

```yaml
--8<-- "snip/test.yaml"
```

## Broken section

This does not work (even though the same code worked above)?

```yaml
--8<--
snip/test.yaml
--8<--
```

Still invisible:

--8<--
snip/test.yaml
--8<--

Still broken:

```yaml

--8<--
snip/test.yaml
--8<--

```

</pre>

snip/test.yaml:

<pre>
# Test:
---
example: file
</pre>

### Actual behavior

<img width="926" alt="image" src="https://user-images.githubusercontent.com/3250776/54226257-abe49180-44ba-11e9-9584-400d128ac147.png">

### Package versions

`squidfunk/mkdocs-material:latest` pulled today.

### Project configuration

``` yaml
...
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
```
