### ISSUE TITLE
MagicLink GitHub Enterprise Support 

### ISSUE THREAD

**Issue by nathanph** [facelessuser/pymdown-extensions#583]
# Request

I'd like to be able to reference GitHub Enterprise repositories in a similar fashion to how one would reference GitHub repositories. The same might as well work for GitLab and BitBucket.

## Usage

I want to be able to define custom providers, e.g, `github`, `pymdownx`, and `mirror` which could be referenced via `@github`, `@pymdownx`, or `@mirror`.

So if I did something like `@mirror` I would expect a link something like this to be generated `[mirror/pymdown-extensions](https://github.enterprise.com/mirror/pymdown-extensions)`.

And if I set the default provider to `pymdownx` and did `#1` I would get `[facelessuser/pymdown-extensions](https://github.com/facelessuser/pymdown-extensions/issues/1)`.

# Proposal

1. Allow users to pass in options to define custom providers.
2. Redefine the current model of a `provider` as more of a template which reflects how data should be parsed and represented.

## Identified Configuration Changes

I think practically what that would mean is changing the configuration options to look something like this:

```yaml
# This is the default provider to use.
provider: pymdownx

# This is a collection of providers you provide.
providers:
  # This is the github provider, I'm listing it explicitly as an example
  # but it should exist by default. The same is true for gitlab and bitbucket.
  # Using an identical name would merge properties. 
  - name: GitHub
    provider: github
    url: https://github.com
  
  # This is this repository!
  - name: Python Markdown Extensions
    provider: pymdownx
    template: github
    user: facelessuser
    repo: pymdown-extensions 

  # This is a mirror of pymdownx hosted by enterprise.com.
  - name: A Python Markdown Extensions Mirror
    template: pymdownx
    url: https://github.enterprise.com/[maybe_some_path?]
    user: mirror
```

## Identified Code Changes

There's a few code changes I've immediately identified and considered in order to support this request.
I think most of these changes will revolve around the way the regular expressions are defined currently.

### `PROVIDER_INFO`

The current `PROVIDER_INFO` info should be composed of just shape information.

```py
PROVIDER_INFO = {
    "gitlab": {
        "provider": "GitLab",
        "url": "https://gitlab.com",
        "user_pattern": RE_GITLAB_USER,
        "issue": "%s/%s/issues/%s",
        "pull": "%s/%s/merge_requests/%s",
        "commit": "%s/%s/commit/%s",
        "compare": "%s/%s/compare/%s...%s",
        "hash_size": 8
    },
    "bitbucket": {
        "provider": "Bitbucket",
        "url": "https://bitbucket.org",
        "user_pattern": RE_BITBUCKET_USER,
        "issue": "%s/%s/issues/%s",
        "pull": "%s/%s/pull-requests/%s",
        "commit": "%s/%s/commits/commit/%s",
        "compare": "%s/%s/branches/commits/%s..%s#diff",
        "hash_size": 7
    },
    "github": {
        "provider": "GitHub",
        "url": "https://github.com",
        "user_pattern": RE_GITHUB_USER,
        "issue": "%s/%s/issues/%s",
        "pull": "%s/%s/pull/%s",
        "commit": "%s/%s/commit/%s",
        "compare": "%s/%s/compare/%s...%s",
        "hash_size": 7
    }
}
```

_Note: I'm ignoring Twitter here because I haven't really put any thought into that._

Honestly, you might even be able to keep the `PROVIDER_INFO` the way it is. Whenever a new provider is defined you can just clone the `provider` it's based off of, replace anything that has been overridden (the `url` and `provider` properties come to mind), then loop over each of the properties replacing the original `url` part with whatever `url` the user provided. In this way you could even extend non-default providers.

### `RE_REPO_LINK_EXPRESSION`

Certainly the compiled `RE_REPO_LINK_EXPRESSION` would have to change to support additional URLs. Probably just build the string up on initialization and then compile it once all of the providers have been processed.

## Comments

I started to do this myself to make a PR but it turned out to be a bit more work than I realized it would be. If this is something you'd be interested in implementing let me know. I've at least thought about what the design would look like a bit.

**Comment by facelessuser** [comment]
So, I'm confused about the first part about specifying custom providers. `@github`, `@pymdownx`, etc. would be very confusing as `@XXXXX` represents a user, not a provider. Providers are only used when doing something like `@provider:user/repo`. It's possible I am just misunderstanding, but I have no intention of changing conventions. With that said, a custom provider is maybe possible.

So if I understand correctly, the request is to create some kind of custom link rules of either type: `github`, `bitbucket`, or `gitlab` (ignoring `twitter` as I don't think it makes sense to have a custom one of these). The only two real variables would be the `base_url` and the `custom_name`, correct?

Essentially, we just want to allow the user to do something like:

```
custom_provider:
    provider: custom
    type: github
    base: https://github.enterprise.com/[maybe_some_path?]
```

And then they can could potentially specify the default provider as `custom` (if desired) and additionally specify links via `@custom:user/repo` etc.

As you mentioned, I imagine the regular expression building would be more dynamic.

Am I understanding correctly?  Does this description sound acceptable (keeping in mind that this is all hypothetical at this point)?
