### ISSUE TITLE
Error: Failed loading extension "pymdownx.arithmatex". 

### ISSUE THREAD

**Issue by HRSlab** [facelessuser/pymdown-extensions#631]
Hi @facelessuser 

I'm using **pymdown-extensions** with **mkdocs** and **mkdocs-material**.

 I get this error when running `mkdocs serve`:

> ERROR   -  Config value: 'markdown_extensions'. Error: Failed loading extension "pymdownx.arithmatex". 

### Here my configuration file:

```yml
theme:
  name: null
  custom_dir: mkdocs-material/material
  language: en
  palette:
    primary: 'blue'
    accent: 'light blue'
  font:
    text: Titillium Web
    code: Roboto Mono
  logo: 'images/HRSlogo-rounded-base.png'
  feature:
    tabs: false

extra_css:
  -  stylesheets/extra.css
  
extra_javascript:
  -  'javascripts/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(smart_enable=all)
  - pymdownx.tilde
```

### Versions:

- Markdown Version: `__main__.py 3.1.1`
- mkdocs-material `Version: 4.3.1`
- Python `Version: 2.7.10`

### Screenshot:

<img width="882" alt="Screen Shot 2019-07-23 at 11 01 11" src="https://user-images.githubusercontent.com/44086439/61698928-37f4a880-ad3a-11e9-807e-acb027775fdd.png">
