### ISSUE TITLE
custom_fences in 6.0 don't work in mkdocs

### ISSUE THREAD

**Issue by Zelgius** [facelessuser/pymdown-extensions#634]
I currently can't add a custom fence to add the UML diagrams back to superfences in mkdocs. When I run `mkdocs serve` I get the following error
```
mkdocs serve
INFO    -  Building documentation...
ERROR   -  Config value: 'markdown_extensions'. Error: Invalid Markdown Extensions configuration

Aborted with 1 Configuration Errors!
```
Relevant information (install packages and config) below.

Packages installed
```pip freeze
Click==7.0
htmlmin==0.1.12
Jinja2==2.10.1
jsmin==2.2.2
livereload==2.6.1
Markdown==3.1.1
MarkupSafe==1.1.1
mkdocs==1.0.4
mkdocs-material==4.4.0
mkdocs-minify-plugin==0.2.1
Pygments==2.4.2
pymdown-extensions==6.0
PyYAML==5.1.1
six==1.12.0
tornado==6.0.3
```

Relevant mkdocs config
```
markdown_extensions:
    - pymdownx.superfences:
      custom_fences:
        - name: flow
          class: uml-flowchart
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: sequence
          class: uml-sequence-diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.progressbar
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.magiclink:
        repo_url_shortener: True
        repo_url_shorthand: True
        social_url_shorthand: True
        # more options on magiclink https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/#options
        provider: 'github'
    - codehilite:
        # https://help.farbox.com/pygments.html
        pygments_style: 'pastie'
        linenums: False
        # set to false to turn off pygments_style
        noclasses: True
    - pymdownx.tasklist
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
    - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
    - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
    - js/loader.js
    - js/details.js
extra_css:
    - css/progress_bar.css
    - css/details.css
    - css/tasklist.css
    - css/custom_tasklist.css
    - css/extra.css
```
