### ISSUE TITLE
Emoji causes mkdocs crash/build failure

### ISSUE THREAD

**Issue by Stanzilla** [facelessuser/pymdown-extensions#768]
I used :tada: in a page today and it crashed it

```
7:49:55 AM: ERROR   -  Error reading page 'news/events/game_jam.md': 'str' object is not callable
7:49:55 AM: Traceback (most recent call last):
7:49:55 AM:   File "/opt/buildhome/python3.7/bin/mkdocs", line 8, in <module>
7:49:55 AM:     sys.exit(cli())
7:49:55 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 764, in __call__
7:49:55 AM:     return self.main(*args, **kwargs)
7:49:55 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
7:49:55 AM:     rv = self.invoke(ctx)
7:49:55 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
7:49:55 AM:     return _process_result(sub_ctx.command.invoke(sub_ctx))
7:49:55 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 956, in invoke
7:49:55 AM:     return ctx.invoke(self.callback, **ctx.params)
7:49:55 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
7:49:55 AM:     return callback(*args, **kwargs)
7:49:55 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/__main__.py", line 163, in build_command
7:49:55 AM:     ), dirty=not clean)
7:49:55 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
7:49:55 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/commands/build.py", line 274, in build
7:49:55 AM:     _populate_page(file.page, config, files, dirty)
7:49:55 AM:   File "/opt/buildhome/python3.7/lib/python3.7/site-packages/mkdocs/commands/build.py", line 177, in _populate_page
7:49:55 AM:     page.render(config, files)
7:49:55 AM: Shutting down logging, 30 messages pending
```

 my markdown_extensions page looks like this:

```yaml
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
```
