### ISSUE TITLE
Tabbed doesn't work as expected for some reason

### ISSUE THREAD

**Issue by stepan-3** [facelessuser/pymdown-extensions#871]
I am trying to use Tabbed (7.0rc2). But it doesn't work as expected.

Screenshot: 
![image](https://user-images.githubusercontent.com/56981806/78204167-b703ba00-744d-11ea-875c-8b6fcbfabdc6.png)

I am using an example from the official docs. 

```
# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.sane_lists
  - markdown.extensions.nl2br
  - prependnewline #plugin to make list behavior, such as we have in GitBook now
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - sane_lists
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed # doesn't work in the Default MkDocs-Material docker
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      check_paths: true
      base_path: docs
```

```
Collecting PyYAML>=3.10
25
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
26
Collecting Jinja2>=2.10.1
27
  Downloading Jinja2-2.11.1-py2.py3-none-any.whl (126 kB)
28
Requirement already satisfied: setuptools>=36 in /opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages (from markdown>=3.2->-r requirements.txt (line 24)) (41.2.0)
29
Collecting six
30
  Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
31
Collecting future>=0.16.0
32
  Downloading future-0.18.2.tar.gz (829 kB)
33
Collecting nltk>=3.2.5; extra == "languages"
34
  Downloading nltk-3.4.5.zip (1.5 MB)
35
Collecting MarkupSafe>=0.23
36
  Downloading MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl (32 kB)
37
Installing collected packages: six, tornado, livereload, future, nltk, lunr, markdown, click, PyYAML, MarkupSafe, Jinja2, mkdocs, Pygments, pymdown-extensions, prependnewline
38
    Running setup.py install for tornado: started
39
    Running setup.py install for tornado: finished with status 'done'
40
    Running setup.py install for future: started
41
    Running setup.py install for future: finished with status 'done'
42
    Running setup.py install for nltk: started
43
    Running setup.py install for nltk: finished with status 'done'
44
    Running setup.py install for PyYAML: started
45
    Running setup.py install for PyYAML: finished with status 'done'
46
    Running setup.py install for prependnewline: started
47
    Running setup.py install for prependnewline: finished with status 'done'
48
Successfully installed Jinja2-2.11.1 MarkupSafe-1.1.1 PyYAML-5.3.1 Pygments-2.6.1 click-7.1.1 future-0.18.2 livereload-2.6.1 lunr-0.5.6 markdown-3.2.1 mkdocs-1.1 nltk-3.4.5 prependnewline-1.2 pymdown-extensions-7.0rc2 six-1.14.0 tornado-6.0.4
```
