### ISSUE TITLE
`!!` not recognized on ReadTheDocs

### ISSUE THREAD

**Issue by pbek** [facelessuser/pymdown-extensions#892]
Thank you for this great extension. I use if for example on https://docs.qownnotes.org/ for mermaid-js support!

My question is if there is a way to get around those `!!` in the `mkdocs.yml`, for example in:

```yml
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # this doesn't work on ReadTheDocs, we need to use `<div class="mermaid"></div>` instead
          format: !!python/name:pymdownx.superfences.fence_div_format
```

ReadTheDocs is parsing the `mkdocs.yml` file using `pyyaml` and it seems that it does not recognize `!!`.

See: https://github.com/readthedocs/readthedocs.org/issues/6889
