### ISSUE TITLE
How can I set a default language for inlinehilite?

### ISSUE THREAD

**Issue by scooby** [facelessuser/pymdown-extensions#910]
I'm working on a document in mkdocs about a single language, so "use this language unless I say so" would be the best behavior for code in backticks.

### Answer

Use the `custom_inline` config setting, a detailed example is in comments on #908 but in short:

```py3
def my_custom_function(src, language, class_name, md):
    """Test custom."""

    if not language:
        language = 'py3'

    return md.inlinePatterns['backtick'].highlight_code(src, language, class_name, md)
```

In `mkdocs.yml`:

```yaml
markdown_extensions:
  - pymdownx.inlinehilite:
      custom_inline:
        - name: '*'
          class: highlight
          format: !!python/name:my_custom_module.my_custom_function
```
