### ISSUE TITLE
progressbar extension won't render properly

### ISSUE THREAD

**Issue by ofek** [facelessuser/pymdown-extensions#912]
```
# Goals

-----

[=25% "25%"]
```

```
mkdocs>=1.1.0
mkdocs-material>=5.1.1
pymdown-extensions>=7.1
```

```yaml
markdown_extensions:
  # Built-in
  - markdown.extensions.abbr:
  - markdown.extensions.admonition:
  - markdown.extensions.footnotes:
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      permalink: true
      toc_depth: "2-6"
  # Extra
  - mkdocs-click:
  - mkpatcher:
      location: docs/developer/.scripts
  - pymdownx.arithmatex:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.details:
  - pymdownx.emoji:
      # https://github.com/twitter/twemoji
      # https://raw.githubusercontent.com/facelessuser/pymdown-extensions/master/pymdownx/twemoji_db.py
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      guess_lang: false
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite:
  - pymdownx.keys:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shortener: true
      social_url_shorthand: true
      provider: github
      user: DataDog
      repo: integrations-core
  - pymdownx.mark:
  - pymdownx.progressbar:
  - pymdownx.smartsymbols:
  - pymdownx.snippets:
      base_path: docs/developer/.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tabbed:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde:
```

## without recommended css

![Capture](https://user-images.githubusercontent.com/9677399/80328562-ae649080-880d-11ea-88bc-297cb748bd83.PNG)

## with recommended css

![Capture](https://user-images.githubusercontent.com/9677399/80328683-07ccbf80-880e-11ea-9fa7-57ad33b6c0bd.PNG)
