### ISSUE TITLE
How to create custom superfences formatter?

### ISSUE THREAD

**Issue by Zebradil** [facelessuser/pymdown-extensions#928]
I was looking through the [uml-diagram-example](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#uml-diagram-example), but I can't figure out how to implement custom formatter instead of using one of the default ones. 

In the example, processing is done by mermaid library on the client side. Instead, I want to process content of a superfenced block on backend during `mkdocs build`.

That's what I have in my config file:

```yaml
markdown_extensions:
  ...
  - pymdownx.superfences
      custom_fences:
        - name: graphviz
          class: graphviz
          format: !!python/name:<custom formatter function>
```

In the docs there is an example format function:

```python
def custom_format(source, language, class_name, options, md):
    """Custom format."""

    return '<div class_name="%s %s", data-option="%s">%s</div>' % (language, class_name, options['opt'], html_escape(source))
```

Where should I put it?

Should I now create a new python module and install it or it's possible to access python source code from local file?

**Comment by facelessuser** [comment]
I'm not sure if what you are posting is a generalized example or what you literally have in your MkDocs file.  `format: !!python/name:<custom formatter function>` doesn't quite look right, so I am assuming this is just a generalized example?

Anyways, you have to reference the full module path of the function which is covered in the docs:  https://facelessuser.github.io/pymdown-extensions/faq/#function-references-in-yaml. Maybe that isn't made clear enough in the docs?

Anyways, you can see how we use them in our own `mkdocs.yml` file:

```yml
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
```

Notice that if you were to look in the source, `pymdownx.superfences.fence_code` is the actual Python import path for that function. Same with `pymdownx.arithmatex.fence_mathjax`.

So, if you had some Python file named `mycustomfile.py` with a formatter function named `mycustomformatter`, you'd specify:

```js
  - pymdownx.superfences
      custom_fences:
        - name: graphviz
          class: graphviz
          format: !!python/name:mycustomfile.mycustomformatter
```

Now, the above assumes your `mycustomfile` is installed. If it isn't, and we can pretend it is in the root of your project, then running `python3 -m mkdocs serve` (the `-m` would allow it to load modules in the CWD directory) would then allow it find your local file. If you have your custom function in a folder, make sure that folder has an `__init__.py` so it is treated as module.

So we'll go with an extremely basic example. Here we create a simple file called `custom.py` in the root of our project. We add the following function. 

```py
def custom_format(source, language, css_class, options, md, **kwargs):
    """Custom format."""

    return '<div>Hello world!</div>'
```

Notice we include `**kwargs` as the latest format signature accepts some keyword arguments as well: https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#formatters. This may vary depending on what version of Pymdown Extensions you are using. I think in the latest version we emit a warning if you forget to account for those keyword arguments.

Anyways, then we can specify:

```yml
  - pymdownx.superfences:
      custom_fences:
        - name: hello
          class: hello
          format: !!python/name:custom.custom_format
```

And when we insert the following:

````
```hello
content doesn't matter
```
````

It will replace it with `<div>Hello world!</div>` when we run `python3 -m mkdocs serve`. Notice we use `-m` to load the local file. If you install your custom function, you don't have to use `-m`.
