### ISSUE TITLE
Superfences / Custom Fences: Preventing escape of HTML characters: loose mode?

### ISSUE THREAD

**Issue by fralau** [facelessuser/pymdown-extensions#964]
Thanks for pymdown-extensions: it's an awsome piece of software.

With mkdocs, I successfully applied superfences / [custom fences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#custom-fences) to correctly display a mermaid diagram, while keeping the color highlighting. 👍

```yaml
markdown_extensions:
  - ...
  - ...
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
```

The plugin for mermaid which I am maintaining ([mkdocs-mermaid2](https://github.com/fralau/mkdocs-mermaid2-plugin) now works _together_ with code highlighting, which is great.

I have also documented that solution on the [plugin's README](https://github.com/fralau/mkdocs-mermaid2-plugin#i-cant-have-highlighting-of-code-and-mermaid-diagrams-at-the-same-time).

I now have a **secondary problem**: I use the **loose** mode with the javascript library of mermaid, in order to be able to insert actual HTML in the mermaid diagrams, so as to get hyperlinks, bold, small, etc.. So my graph contains HTML code.

This is how one does it in the plugin:

```yaml
plugins:
  - ...
  - mermaid2:
      arguments:
        securityLevel: 'loose'
```

Which translate into the following argument for the javascript call:
```json
{'securityLevel': 'loose'}
```

See where this is going? 🙂

The problem is that superfences (no doubt wisely) **choses to convert HTML brackets (`<`and '>') into HTML entities, to avoid interference with HTML**, as well as (I reckon) code injection.

Yet HTML code is what I want in my mermaid graph code for that specific mkdocs project (which is why I have activated the loose mode in mermaid).

The result, is that the HTML is now displayed _verbatim_ in the diagram:
![Capture d’écran 2020-05-29 à 17 36 26](https://user-images.githubusercontent.com/36767124/83277856-f55df100-a1d2-11ea-81a6-8cd4256488d5.png)

Of course, I could force the plugin to work its way back from the HTML entities toward the HTML brackets so that it displays correctly, but _there must be a better way_.

Would there be a way to tell the `custom_fences`: "please to not translate the HTML characters into entities"? Sort of a "loose mode"?
